<center><font color=red>
    <h1>NUMPY</h1>
</font>
</center>

### CREAR UNA MATRIZ

In [12]:
import numpy as np

matriz_int = np.full((2,3), 0, int)
matriz_float = np.full((2,3), 0.0, float)
matriz_str = np.full((2,3), '', str)
matriz_bool = np.full((2,3), False, bool)

print('Matriz Enteros: ',matriz_int)
print('Matriz Reales : ',matriz_float)
print('Matriz Cadenas: ',matriz_str)
print('Matriz Lógico : ',matriz_bool)



Matriz Enteros:  [[0 0 0]
 [0 0 0]]
Matriz Reales :  [[0. 0. 0.]
 [0. 0. 0.]]
Matriz Cadenas:  [['' '' '']
 ['' '' '']]
Matriz Lógico :  [[False False False]
 [False False False]]


### RECORRER UNA MATRIZ

In [ ]:
import numpy as np

matriz_int = np.full((5,6), 0, int)

dimension = matriz_int.shape

nf = dimension[0]
nc = dimension[1]

for i in range(nf):
    for j in range(nc):
        print(matriz_int[i][j],end='  ')
    print()


### DEFINIR UNA MATRIZ DINAMICA

In [3]:
import numpy as np


def mostrar(matriz_int):
    dimension = matriz_int.shape
    nf = dimension[0]
    nc = dimension[1]
    for i in range(nf):
        for j in range(nc):
            print(matriz_int[i][j],end='  ')
        print()
    

def entrada():
    nf = numeroEntero('Cantidad filas? ')
    nc = numeroEntero('Cantidad columnas? ')

    matriz_int = np.full((nf,nc), 0, int)

    for i in range(nf):
        for j in range(nc):
            print('matriz_int[',i,'][',j,'] = ', end='')
            matriz_int[i][j] = numeroEntero('Ingrese número entero? ')
            
    mostrar(matriz_int)

entrada()



Cantidad filas? 2
Cantidad columnas? 3
matriz_int[ 0 ][ 0 ] = Ingrese número entero? 8
matriz_int[ 0 ][ 1 ] = Ingrese número entero? 9
matriz_int[ 0 ][ 2 ] = Ingrese número entero? 2
matriz_int[ 1 ][ 0 ] = Ingrese número entero? 4
matriz_int[ 1 ][ 1 ] = Ingrese número entero? 5
matriz_int[ 1 ][ 2 ] = Ingrese número entero? 1
8  9  2  
4  5  1  


### VECTOR

In [11]:
import numpy as np

# DECLAR UN VECTOR

vector_int = np.empty(0, dtype=int)
vector_float = np.empty(0, float)
vector_str = np.empty(0, str)
vector_bool = np.empty(0, bool)

print(vector_int)
print(vector_float)
print(vector_str)
print(vector_bool)

# lLENAR UN VECTOR DINAMICAMENTE

n = numeroEntero('Tamaño del vector? ')

vector_int = np.empty(n, dtype=int)

for i in range(n):
    print('vector_int[',i,'] = ',end='')
    vector_int[i] = numeroEntero('Ingrese número entero? ')
    
print(vector_int)

[]
[]
[]
[]
Tamaño del vector? 5
vector_int[ 0 ] = Ingrese número entero? 8
vector_int[ 1 ] = Ingrese número entero? 3
vector_int[ 2 ] = Ingrese número entero? 9
vector_int[ 3 ] = Ingrese número entero? 1
vector_int[ 4 ] = Ingrese número entero? 6
[8 3 9 1 6]


### LIBRERIAS

In [1]:
import re

def numeroReal(mensaje): # 3434 o 234.24
    patron = '[0-9]+||[0-9]+\.[0-9]{1,2}'
    while True:
          cadena = input(mensaje)
          correcto = re.fullmatch(patron,cadena)
          if not correcto:
             print("Error: Vuelva a ingresar el dato")
          else:
             break
    return float(cadena)

def entradaNombre(mensaje): # letras del alfabeto
    patron = '[a-zA-ZñÑáéíóúÁÉÍÓÚ]+'
    while True:
          cadena = input(mensaje)
          correcto = re.fullmatch(patron,cadena)
          if not correcto:
             print("Error: Vuelva a ingresar el dato")
          else:
             break
    return cadena

def numeroEntero(mensaje): 
    patron = '[0-9]+'
    while True:
          cadena = input(mensaje)
          correcto = re.fullmatch(patron,cadena)
          if not correcto:
             print("Error: Vuelva a ingresar el dato")
          else:
             break
    return int(cadena) 